import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import SideNavBar from "./components/SideNavBar";
import { isBrowser, isMobile, BrowserView, MobileView } from "react-device-detect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-y-hidden">
        <NavBar />
        {children}
        <SideNavBar />
      </body>
    </html>
  );
}
